// WLED effects list - Curated selection of practical effects
// Reference: https://kno.wled.ge/features/effects/

export interface WledEffect {
	id: number;
	name: string;
}

// Full WLED effects list (for reference and ID mapping)
const WLED_EFFECTS_FULL = [
	'Solid',           // 0
	'Blink',
	'Breathe',
	'Wipe',
	'Wipe Random',
	'Random Colors',
	'Sweep',
	'Dynamic',
	'Colorloop',
	'Rainbow',
	'Scan',            // 10
	'Scan Dual',
	'Fade',
	'Theater',
	'Theater Rainbow',
	'Running',
	'Saw',
	'Twinkle',
	'Dissolve',
	'Dissolve Rnd',
	'Sparkle',         // 20
	'Sparkle Dark',
	'Sparkle+',
	'Strobe',
	'Strobe Rainbow',
	'Strobe Mega',
	'Blink Rainbow',
	'Android',
	'Chase',
	'Chase Random',
	'Chase Rainbow',   // 30
	'Chase Flash',
	'Chase Flash Rnd',
	'Rainbow Runner',
	'Colorful',
	'Traffic Light',
	'Sweep Random',
	'Chase 2',
	'Aurora',
	'Stream',
	'Scanner',         // 40
	'Lighthouse',
	'Fireworks',
	'Rain',
	'Tetrix',
	'Fire Flicker',
	'Gradient',
	'Loading',
	'Rolling Balls',
	'Fairy',
	'Two Dots',        // 50
	'Fairytwinkle',
	'Running Dual',
	'RSVD',
	'Chase 3',
	'Tri Wipe',
	'Tri Fade',
	'Lightning',
	'ICU',
	'Multi Comet',
	'Scanner Dual',    // 60
	'Stream 2',
	'Oscillate',
	'Pride 2015',
	'Juggle',
	'Palette',
	'Fire 2012',
	'Colorwaves',
	'Bpm',
	'Fill Noise',
	'Noise 1',         // 70
	'Noise 2',
	'Noise 3',
	'Noise 4',
	'Colortwinkles',
	'Lake',
	'Meteor',
	'Meteor Smooth',
	'Railway',
	'Ripple',
	'Twinklefox',      // 80
	'Twinklecat',
	'Halloween Eyes',
	'Solid Pattern',
	'Solid Pattern Tri',
	'Spots',
	'Spots Fade',
	'Glitter',
	'Candle',
	'Fireworks Starburst',
	'Fireworks 1D',    // 90
	'Bouncing Balls',
	'Sinelon',
	'Sinelon Dual',
	'Sinelon Rainbow',
	'Popcorn',
	'Drip',
	'Plasma',
	'Percent',
	'Ripple Rainbow',
	'Heartbeat',       // 100
	'Pacifica',
	'Candle Multi',
	'Solid Glitter',
	'Sunrise',
	'Phased',
	'Twinkleup',
	'Noise Pal',
	'Sine',
	'Phased Noise',
	'Flow',            // 110
	'Chunchun',
	'Dancing Shadows',
	'Washing Machine',
	'Rotozoomer',
	'Blends',
	'TV Simulator',
	'Dynamic Smooth',
	'Spaceships',
	'Crazy Bees',
	'Ghost Rider',     // 120
	'Blobs',
	'Scrolling Text',
	'Drift Rose',
	'Distortion Waves',
	'Soap',
	'Octopus',
	'Waving Cell',
	'Pixels',
	'Pixelwave',
	'Juggles',         // 130
	'Matripix',
	'Gravimeter',
	'Plasmoid',
	'Puddles',
	'Midnoise',
	'Noisemeter',
	'Freqwave',
	'Freqmatrix',
	'GEQ',
	'Waterfall',       // 140
	'Freqpixels',
	'RSVD',
	'Noisefire',
	'Puddlepeak',
	'Noisemove',
	'Noise2D',
	'Perlin Move',
	'Ripple Peak',
	'Firenoise',
	'Squared Swirl',   // 150
	'RSVD',
	'DNA',
	'Matrix',
	'Metaballs',
	'Freqmap',
	'Gravcenter',
	'Gravcentric',
	'Gravfreq',
	'DJ Light',
	'Funky Plank',     // 160
	'RSVD',
	'Pulser',
	'Blurz',
	'Drift',
	'Waverly',
	'Sun Radiation',
	'Colored Bursts',
	'Julia',
	'RSVD',
	'RSVD',            // 170
	'RSVD',
	'Game Of Life',
	'Tartan',
	'Polar Lights',
	'Swirl',
	'Lissajous',
	'Frizzles',
	'Plasma Ball',
	'Flow Stripe',
	'Hiphotic',        // 180
	'Sindots',
	'DNA Spiral',
	'Black Hole',
	'Wavesins',
	'Rocktaves',
	'Akemi',           // 186
];

// Curated effects - only the practical and visually interesting ones
const CURATED_EFFECT_NAMES = [
	'Blurz',
	'Bouncing Balls',
	'Chunchun',
	'Fire 2012',
	'Gravcenter',
	'Gravcentric',
	'Halloween Eyes',
	'Heartbeat',
	'Lightning',
	'Loading',
	'Noisefire',
	'Noisemove',
	'Pixelwave',
	'Puddlepeak',
	'Puddles',
	'Rain',
	'Ripple',
	'Ripple Peak',
	'Rocktaves',
	'Scan Dual',
	'Scan',
	'Sine',
	'Sinelon Dual',
	'Solid',
	'Solid Glitter',
	'Sparkle',
	'Strobe',
	'Strobe Mega',
	'Tri Wipe',
	'Twinkle',
	'Wavesins',
	'Wipe',
];

// Map curated effect names to their IDs
export const WLED_EFFECTS: WledEffect[] = CURATED_EFFECT_NAMES
	.map(name => {
		const id = WLED_EFFECTS_FULL.indexOf(name);
		return id >= 0 ? { id, name } : null;
	})
	.filter((effect): effect is WledEffect => effect !== null)
	.sort((a, b) => a.name.localeCompare(b.name));
